### ISSUE TITLE
Add custom logger to log all the things

### ISSUE THREAD

**Issue by stronk-dev** [koiosdev/chordTabsToPrintables#19]
Enabling all prints in the code will cause a very spammy output in the console.

We would like to have a custom print function, which also takes into consideration a log level:
3. debug
2. info
1. warning
0. errors

The log level can then be defined in the config file
For each existing print in the program, we should call the custom print function and tell it type of print (debug, info, warning, error) it is

Since using 0, 1, 2, 3 for choosing a log type is annoying to program with, it would also be useful to define a set of global variables somewhere:
LVL_DEBUG=0,  LVL_INFO=1,  LVL_WARNING=2, LVL_ERROR=3
and import them into each file

**Comment by Theocat321** [comment]
Have done re-enabling the prints, what do you mean by sending them to various print levels in config?

**Comment by stronk-dev** [comment]
Hi theocat, 
Cool to see someone else take interest into the project!
I've updated the description to be a bit more descriptive, hope it helps!

**Comment by Theocat321** [comment]
Ill give it a go tommorow!

**Comment by stronk-dev** [comment]
Implemented using the built in logging module in 4ab8f6c836b7f1fd2650b3d0b37ca432c94f9f2f
